package com.yourorg.jmoa.plugin.framework;

public enum FrameworkSafetyReason {
    PROJECT_OUTPUT_CLASS,
    SAFE_ADDITIONAL_DIRECTORY,
    SAFE_EXPANDED_DEPENDENCY_PREFIX,
    SAFE_SPRING_AOT_CLASS,
    COLD_PROFILED_SITE,
    SAFE_SAM_KIND,
    MISSING_PROFILE,
    HOT_SITE,
    CAPTURING_LAMBDA,
    SERIALIZABLE_LAMBDA,
    UNSUPPORTED_SAM_KIND,
    SPRING_REFLECTION_PACKAGE,
    JACKSON_INTERNAL_PACKAGE,
    HIBERNATE_INTERNAL_PACKAGE,
    PROXY_OR_ENHANCER_PACKAGE,
    UNKNOWN_FRAMEWORK_PACKAGE,
    EXPANDED_DEPENDENCY_DISABLED,
    SPRING_AOT_DISABLED,
    OBSERVED_SITE_KEY_ADMITTED
}
